language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '1.0.0'
  - '2.0.0'
  - '3.0.0'
  - '4.0.0'
before_script:
  - npm install -g grunt-cli
matrix:
  fast_finish: true
  allow_failures:
    # - node_js: '0.11'
